// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/password': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/password.patch').default>>>>
    }
    '/api/auth/setup': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/setup.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/setup.post').default>>>>
    }
    '/api/comics/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comics/[id]').default>>>>
    }
    '/api/comics/:id/enhance': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comics/[id]/enhance.post').default>>>>
    }
    '/api/comics/:id/enhance/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comics/[id]/enhance/status.get').default>>>>
    }
    '/api/comics/:id/match': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comics/[id]/match.post').default>>>>
    }
    '/api/comics/:id/pages/:page': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comics/[id]/pages/[page].get').default>>>>
    }
    '/api/comics/:id/suggestions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comics/[id]/suggestions.get').default>>>>
    }
    '/api/comics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comics/index.get').default>>>>
    }
    '/api/covers/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/covers/[id].get').default>>>>
    }
    '/api/covers/by-slug/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/covers/by-slug/[slug].get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/library/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/library/[id]').default>>>>
    }
    '/api/library': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/library/index').default>>>>
    }
    '/api/scan': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/scan.post').default>>>>
    }
    '/api/scan/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/scan/status.get').default>>>>
    }
    '/api/settings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings/index').default>>>>
    }
    '/api/users/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.post').default>>>>
    }
  }
}
export {}